AWSTemplateFormatVersion: 2010-09-09
Description: Baseline-CloudCheckr Template.
  This creates Baseline CloudCheckr Role needed by CloudCheckr.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CloudCheckr Configuration
        Parameters:
          - CloudCheckrAccountID
          - CloudCheckrExternalID
    ParameterLabels:
      CloudCheckrAccountID:
        default: CloudCheckr Account ID
      CloudCheckrExternalID:
        default: CloudCheckr External ID
Parameters:
  CloudCheckrAccountID:
    Description: Enter the CloudCheckr 3rd party Account ID
    Type: String
    Default: ''
  CloudCheckrExternalID:
    Description: Enter the CloudCheckr 3rd party External ID
    Type: String
    Default: ''
Resources:
  CloudCheckrRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${CloudCheckrAccountID}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref CloudCheckrExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
    DeletionPolicy: Retain
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudCheckrPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AdditionalPermissions
            Effect: Allow
            Action:
              - cloudformation:GetStackPolicy
              - cloudhsm:Describe*
              - cloudhsm:List*
              - glacier:List*
              - glacier:DescribeVault
              - glacier:GetVaultNotifications
              - glacier:DescribeJob
              - glacier:GetJobOutput
              - sdb:DomainMetadata
              - support:*
              - workspaces:DescribeWorkspaceDirectories
              - workspaces:DescribeWorkspaceBundles
              - workspaces:DescribeWorkspaces
            Resource: '*'
          - Sid: CloudWatchLogsSpecific
            Effect: Allow
            Action:
              - logs:GetLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource:
              - arn:aws:logs:*:*:*
      Roles:
        - !Ref CloudCheckrRole
    DeletionPolicy: Retain
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref CloudCheckrRole
    DeletionPolicy: Retain
Outputs:
  CloudCheckrARNforAWSCoE:
    Description: Please provide this ARN for the AWS CoE. This ARN is needed to collect account detail
    Value: !GetAtt CloudCheckrRole.Arn
