AWSTemplateFormatVersion: 2010-09-09
Description: Billing-BillingSubscriptions Template.
  This creates Standard Subscriptions to Billing SNS Topics.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BillingTopicsStackName
      - Label:
          default: Subscription Configuration
        Parameters:
          - BillsTopicEmailEndpoint
          - UrgentBillsTopicEmailEndpoint
          - UrgentBillsTopicPhoneEndpoint
    ParameterLabels:
      BillingTopicsStackName:
        default: Billing Topics Stack Name
      BillsTopicEmailEndpoint:
        default: Bills Topic Email Endpoint
      UrgentBillsTopicEmailEndpoint:
        default: UrgentBills Topic Email Endpoint
      UrgentBillsTopicPhoneEndpoint:
        default: UrgentBills Topic Phone Endpoint
Parameters:
  BillingTopicsStackName:
    Description: Name of the CloudFormation Stack containing Billing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: BillingTopics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  BillsTopicEmailEndpoint:
    Description: Email Endpoint for Bills Topic. If blank, no standard subscription will be created
    Type: String
    Default: ''
    AllowedPattern: (^$|[^\s@]+@[^\s@]+\.[^\s@]+$)
    ConstraintDescription: must be a valid email address.
  UrgentBillsTopicEmailEndpoint:
    Description: Email Endpoint for UrgentBills Topic. If blank, no standard subscription will be created
    Type: String
    Default: ''
    AllowedPattern: (^$|[^\s@]+@[^\s@]+\.[^\s@]+$)
    ConstraintDescription: must be a valid email address.
  UrgentBillsTopicPhoneEndpoint:
    Description: Phone Endpoint for BillsSMS Topics. If blank, no standard subscription will be created
    Type: String
    Default: ''
    AllowedPattern: (^$|^\+\d{11,12}$)
    ConstraintDescription: must be a valid phone number.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureBillsTopicEmailSubscription: !Not [ !Equals [ !Ref BillsTopicEmailEndpoint, '' ]]
  ConfigureUrgentBillsTopicEmailSubscription: !Not [ !Equals [ !Ref UrgentBillsTopicEmailEndpoint, '' ]]
  ConfigureUrgentBillsTopicPhoneSubscription: !Not [ !Equals [ !Ref UrgentBillsTopicPhoneEndpoint, '' ]]
Resources:
  BillsTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsTopic
      Protocol: email
      Endpoint: !Ref BillsTopicEmailEndpoint
    Condition: ConfigureBillsTopicEmailSubscription
  UrgentBillsTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: email
      Endpoint: !Ref UrgentBillsTopicEmailEndpoint
    Condition: ConfigureUrgentBillsTopicEmailSubscription
  UrgentBillsTopicPhoneSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: sms
      Endpoint: !Ref UrgentBillsTopicPhoneEndpoint
    Condition: ConfigureUrgentBillsTopicPhoneSubscription
