AWSTemplateFormatVersion: 2010-09-09
Description: Billing-BillingTopics Template.
  This creates Billing SNS Topics.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Topic Configuration
        Parameters:
          - TopicPrefix
    ParameterLabels:
      TopicPrefix:
        default: Topic Prefix
Parameters:
  TopicPrefix:
    Description: Optional Prefix for Topic Display Name
    Type: String
    Default: HLSB
    AllowedPattern: (^&|^[A-Z][A-Z0-9]{1,4}$)
    ConstraintDescription: must begin with an upper-case letter and consist of 1 to 4 additional upper-case letters or digits, if specified.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureTopicPrefix: !Not [ !Equals [ !Ref TopicPrefix, '' ]]
Resources:
  BillsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Bills
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Bills
        - Bills
  BillsSMSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: BillsSMS
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Bills
        - Bills
Outputs:
  BillsTopic:
    Description: The Bills Topic ARN
    Value: !Ref BillsTopic
    Export:
      Name: !Sub ${AWS::StackName}-BillsTopic
  BillsSMSTopic:
    Description: The BillsSMS Topic ARN
    Value: !Ref BillsSMSTopic
    Export:
      Name: !Sub ${AWS::StackName}-BillsSMSTopic
