AWSTemplateFormatVersion: 2010-09-09
Description: Billing-BillingCustomSubscriptions Template.
  This creates Custom Subscriptions to Billing SNS Topics.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BillingTopicsStackName
      - Label:
          default: Subscription Configuration
        Parameters:
          - TopicTestEmailEndpoint
          - UrgentTopicTestPhoneEndpoint
    ParameterLabels:
      BillingTopicsStackName:
        default: Billing Topics Stack Name
      TopicTestEmailEndpoint:
        default: Topic Test Email Endpoint
      UrgentTopicTestEmailEndpoint:
        default: Urgent Topic Test Email Endpoint
      UrgentTopicTestPhoneEndpoint:
        default: Urgent Topic Test Phone Endpoint
Parameters:
  BillingTopicsStackName:
    Description: Name of the CloudFormation Stack containing Billing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: BillingTopics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicTestEmailEndpoint:
    Description: Optional test email Endpoint for Topics. If specified, test Subscriptions will be created instead of normal Subscriptions. Use hyphen to skip
    Type: String
    Default: ''
    AllowedPattern: (^$|^-$|[^\s@]+@[^\s@]+\.[^\s@]+$)
    ConstraintDescription: must be a valid email address.
  UrgentTopicTestEmailEndpoint:
    Description: Optional test email Endpoint for Urgent Topics. If specified, test Subscriptions will be created instead of normal Subscriptions. Use hyphen to skip
    Type: String
    Default: ''
    AllowedPattern: (^$|^-$|[^\s@]+@[^\s@]+\.[^\s@]+$)
    ConstraintDescription: must be a valid email address.
  UrgentTopicTestPhoneEndpoint:
    Description: Optional test Phone Endpoint for Urgent Topics. If specified, test Subscriptions will be created instead of normal Subscriptions. Use hyphen to skip
    Type: String
    Default: ''
    AllowedPattern: (^$|^-$|^\+\d{11,12}$)
    ConstraintDescription: must be a valid phone number.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureNormalTopicEmailSubscriptions: !Equals [ !Ref TopicTestEmailEndpoint, '' ]
  ConfigureTestTopicEmailSubscriptions: !And [ !Not [ !Condition ConfigureNormalTopicEmailSubscriptions ],
                                               !Not [ !Equals [ !Ref TopicTestEmailEndpoint, '-' ]]]
  ConfigureNormalUrgentTopicEmailSubscriptions: !Equals [ !Ref UrgentTopicTestEmailEndpoint, '' ]
  ConfigureTestUrgentTopicEmailSubscriptions: !And [ !Not [ !Condition ConfigureNormalUrgentTopicEmailSubscriptions ],
                                                     !Not [ !Equals [ !Ref UrgentTopicTestEmailEndpoint, '-' ]]]
  ConfigureNormalUrgentTopicPhoneSubscriptions: !Equals [ !Ref UrgentTopicTestPhoneEndpoint, '' ]
  ConfigureTestUrgentTopicPhoneSubscriptions: !And [ !Not [ !Condition ConfigureNormalUrgentTopicPhoneSubscriptions ],
                                                     !Not [ !Equals [ !Ref UrgentTopicTestPhoneEndpoint, '-' ]]]
Resources:
  BillsTopicTestEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsTopic
      Protocol: email
      Endpoint: !Ref TopicTestEmailEndpoint
    Condition: ConfigureTestTopicEmailSubscriptions
  BillsTopicMCrawfordEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-BillsTopic
      Protocol: email
      Endpoint: mcrawford@dxc.com
    Condition: ConfigureNormalTopicEmailSubscriptions
  UrgentBillsTopicTestEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: email
      Endpoint: !Ref UrgentTopicTestEmailEndpoint
    Condition: ConfigureTestUrgentTopicEmailSubscriptions
  UrgentBillsTopicMCrawfordEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: email
      Endpoint: mcrawford@dxc.com
    Condition: ConfigureNormalUrgentTopicEmailSubscriptions
  UrgentBillsTopicTestPhoneSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: sms
      Endpoint: !Ref UrgentTopicTestPhoneEndpoint
    Condition: ConfigureTestUrgentTopicPhoneSubscriptions
  UrgentBillsTopicMCrawfordPhoneSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !ImportValue
        Fn::Sub: ${BillingTopicsStackName}-UrgentBillsTopic
      Protocol: sms
      Endpoint: '+14156525483'
    Condition: ConfigureNormalUrgentTopicPhoneSubscriptions
