AWSTemplateFormatVersion: 2010-09-09
Description: Common-Topics Template.
  This creates SNS Topics. These Topics are used for System Operation and should be in each Region used.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Topic Configuration
        Parameters:
          - TopicPrefix
    ParameterLabels:
      TopicPrefix:
        default: Topic Prefix
Parameters:
  TopicPrefix:
    Description: Optional Prefix for Topic Display Name
    Type: String
    Default: ''
    AllowedPattern: (^$|^[A-Z][A-Z0-9]{1,4}$)
    ConstraintDescription: must begin with an upper-case letter and consist of 1 to 4 additional upper-case letters or digits, if specified.
Conditions:
  ConfigureTopicPrefix: !Not [ !Equals [ !Ref TopicPrefix, '' ]]
Resources:
  EventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Events
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Events
        - Events
  UrgentEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: UrgentEvents
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Events
        - Events
  AlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Alarms
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Alarms
        - Alarms
  UrgentAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: UrgentAlarms
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} Alarms
        - Alarms
  CloudTrailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CloudTrail
      DisplayName: !If
        - ConfigureTopicPrefix
        - !Sub ${TopicPrefix} CloudTrail
        - CloudTrail
  CloudTrailTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudTrailTopic
      PolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: AllowCloudTrailPublish
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: SNS:Publish
            Resource: '*'
Outputs:
  EventsTopic:
    Description: The Events Topic ARN
    Value: !Ref EventsTopic
    Export:
      Name: !Sub ${AWS::StackName}-EventsTopic
  UrgentEventsTopic:
    Description: The UrgentEvents Topic ARN
    Value: !Ref UrgentEventsTopic
    Export:
      Name: !Sub ${AWS::StackName}-UrgentEventsTopic
  AlarmsTopic:
    Description: The Alarms Topic ARN
    Value: !Ref AlarmsTopic
    Export:
      Name: !Sub ${AWS::StackName}-AlarmsTopic
  UrgentAlarmsTopic:
    Description: The UrgentAlarms Topic ARN
    Value: !Ref UrgentAlarmsTopic
    Export:
      Name: !Sub ${AWS::StackName}-UrgentAlarmsTopic
  CloudTrailTopic:
    Description: The CloudTrail Topic ARN
    Value: !Ref CloudTrailTopic
    Export:
      Name: !Sub ${AWS::StackName}-CloudTrailTopic
