AWSTemplateFormatVersion: 2010-09-09
Description: Common-HostedZone Template.
  This creates an Environment HostedZone within an Environment or Core Account. Multiple Environments can co-exist.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HostedZone Configuration
        Parameters:
          - Name
          - PublicDomain
    ParameterLabels:
      Name:
        default: Name
      PublicDomain:
        default: PublicDomain
Parameters:
  Name:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Log
      - Core
      - Build
      - Identity
    ConstraintDescription: 'must be one of the following: Production, Staging, UAT, Testing, Development, Log, Core, Build or Identity.'
  PublicDomain:
    Description: Public Domain associated with the Stack
    Type: String
    MinLength: 7
    MaxLength: 64
    Default: us-west-2.dapj.dxcanalytics.com
    AllowedPattern: ^((?!-)[a-z0-9-]{1,63}(?<!-)\.)+[a-z]{2,10}$
    ConstraintDescription: must be a valid domain name and contain only lower-case letters, numbers, dashes and periods.
Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub Public Zone for ${PublicDomain}
      Name: !Sub ${PublicDomain}.
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${Name}-PublicHostedZone
Outputs:
  PublicHostedZone:
    Description: The PublicHostedZone
    Value: !Ref PublicHostedZone
    Export:
      Name: !Sub ${AWS::StackName}-PublicHostedZone
  PublicDomain:
    Description: The PublicDomain
    Value: !Ref PublicDomain
    Export:
      Name: !Sub ${AWS::StackName}-PublicDomain
