AWSTemplateFormatVersion: 2010-09-09
Description: Common-IdentifierFunctions Template.
  This creates Lambda Functions related to Identifiers.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BucketsStackName
          - TopicsStackName
      - Label:
          default: Function Configuration
        Parameters:
          - IdentifierConverterFunctionKey
          - IdentifierConverterFunctionObjectVersion
          - IdentifierConverterLogRetention
          - HostNameFunctionKey
          - HostNameFunctionObjectVersion
          - HostNameLogRetention
          - DomainNameFunctionKey
          - DomainNameFunctionObjectVersion
          - DomainNameLogRetention
    ParameterLabels:
      BucketsStackName:
        default: Buckets Stack Name
      TopicsStackName:
        default: Topics Stack Name
      IdentifierConverterFunctionKey:
        default: IdentifierConverter Function S3 Key
      IdentifierConverterFunctionObjectVersion:
        default: IdentifierConverter Function S3 Object Version
      IdentifierConverterLogRetention:
        default: IdentifierConverter Log Retention
      HostNameFunctionKey:
        default: HostName Function S3 Key
      HostNameFunctionObjectVersion:
        default: HostName Function S3 Object Version
      HostNameLogRetention:
        default: HostName Log Retention
      DomainNameFunctionKey:
        default: DomainName Function S3 Key
      DomainNameFunctionObjectVersion:
        default: DomainName Function S3 Object Version
      DomainNameLogRetention:
        default: DomainName Log Retention
Parameters:
  BucketsStackName:
    Description: Name of the CloudFormation Stack containing Buckets
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Buckets
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicsStackName:
    Description: Name of the CloudFormation Stack containing Topics
    Type: String
    MinLength: 8
    MaxLength: 64
    Default: Topics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  IdentifierConverterFunctionKey:
    Description: Key of Object within the S3 Bucket containing the IdentifierConverter Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: IdentifierConverter.zip
    AllowedPattern: ^[-_.a-zA-Z0-9]*\.zip$
    ConstraintDescription: must be a valid zipfilename, not containing slashes.
  IdentifierConverterFunctionObjectVersion:
    Description: Version of Object within the S3 Bucket containing the IdentifierConverter Lambda Function zipfile
    Type: String
    MaxLength: 32
    Default: ''
    ConstraintDescription: must be a valid S3 Object Version.
  IdentifierConverterLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the IdentifierConverter Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: 'must be: 1, 3, 5, 7, 14, 30, 60 or 90.'
  HostNameFunctionKey:
    Description: Key of Object within the S3 Bucket containing the HostName Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: HostName.zip
    AllowedPattern: ^[-_.a-zA-Z0-9]*\.zip$
    ConstraintDescription: must be a valid zipfilename, not containing slashes.
  HostNameFunctionObjectVersion:
    Description: Version of Object within the S3 Bucket containing the HostName Lambda Function zipfile
    Type: String
    MaxLength: 32
    Default: ''
    ConstraintDescription: must be a valid S3 Object Version.
  HostNameLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the HostName Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: 'must be: 1, 3, 5, 7, 14, 30, 60 or 90.'
  DomainNameFunctionKey:
    Description: Key of Object within the S3 Bucket containing the DomainName Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: DomainName.zip
    AllowedPattern: ^[-_.a-zA-Z0-9]*\.zip$
    ConstraintDescription: must be a valid zipfilename, not containing slashes.
  DomainNameFunctionObjectVersion:
    Description: Version of Object within the S3 Bucket containing the DomainName Lambda Function zipfile
    Type: String
    MaxLength: 32
    Default: ''
    ConstraintDescription: must be a valid S3 Object Version.
  DomainNameLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the DomainName Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: 'must be: 1, 3, 5, 7, 14, 30, 60 or 90.'
Conditions:
  ConfigureIdentifierConverterFunctionObjectVersion: !Not [ !Equals [ !Ref IdentifierConverterFunctionObjectVersion, '' ]]
  ConfigureHostNameFunctionObjectVersion: !Not [ !Equals [ !Ref HostNameFunctionObjectVersion, '' ]]
  ConfigureDomainNameFunctionObjectVersion: !Not [ !Equals [ !Ref DomainNameFunctionObjectVersion, '' ]]
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  IdentifierConverterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/IdentifierConverter
      RetentionInDays: !Ref IdentifierConverterLogRetention
  IdentifierConverterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: IdentifierConverter
      Description: A Lambda function which converts Identifiers in Upper Case to Lower Case and Codes, which can be used to construct Names.
      Role: !GetAtt Role.Arn
      Runtime: nodejs8.10
      Timeout: 30
      Handler: IdentifierConverter.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref IdentifierConverterFunctionKey
        S3ObjectVersion: !If [ ConfigureIdentifierConverterFunctionObjectVersion, !Ref IdentifierConverterFunctionObjectVersion, !Ref 'AWS::NoValue' ]
  HostNameLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/HostName
      RetentionInDays: !Ref HostNameLogRetention
  HostNameFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HostName
      Description: A Lambda function which creates a HostName that conforms to DXC Prototype Naming Conventions for use by Instances in a VPC, based on Company, Location, (optional) System, Application and (optional) Component.
      Role: !GetAtt Role.Arn
      Runtime: nodejs8.10
      Timeout: 30
      Handler: HostName.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref HostNameFunctionKey
        S3ObjectVersion: !If [ ConfigureHostNameFunctionObjectVersion, !Ref HostNameFunctionObjectVersion, !Ref 'AWS::NoValue' ]
  DomainNameLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/DomainName
      RetentionInDays: !Ref DomainNameLogRetention
  DomainNameFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DomainName
      Description: A Lambda function which creates a DomainName which conforms to DXC Prototype Naming Conventions for use by HostedZones in a VPC, based on Names or Codes associated with the Environment, Location, Company and Parent DomainName.
      Role: !GetAtt Role.Arn
      Runtime: nodejs8.10
      Timeout: 30
      Handler: DomainName.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref DomainNameFunctionKey
        S3ObjectVersion: !If [ ConfigureDomainNameFunctionObjectVersion, !Ref DomainNameFunctionObjectVersion, !Ref 'AWS::NoValue' ]
Outputs:
  IdentifierConverterFunctionArn:
    Description: The IdentifierConverter Lambda Function ARN
    Value: !GetAtt IdentifierConverterFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-IdentifierConverterFunctionArn
  HostNameFunctionArn:
    Description: The HostName Lambda Function ARN
    Value: !GetAtt HostNameFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-HostNameFunctionArn
  DomainNameFunctionArn:
    Description: The DomainName Lambda Function ARN
    Value: !GetAtt DomainNameFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DomainNameFunctionArn
