AWSTemplateFormatVersion: 2010-09-09
Description: Common-PublicRecordSets Template.
  This creates Manual Public RecordSets in a Public HostedZone.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - PublicHostedZoneStackName
      - Label:
          default: RecordSet Configuration
        Parameters:
          - CheckTXTValue
    ParameterLabels:
      PublicHostedZoneStackName:
        default: PublicHostedZone Stack Name
      CheckTXTValue:
        default: Check TXT Value
Parameters:
  PublicHostedZoneStackName:
    Description: Name of the CloudFormation Stack containing the Public HostedZone
    Type: String
    MaxLength: 64
    Default: Production-PublicHostedZone
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  CheckTXTValue:
    Description: Optional value of Check TXT Record (without quotes)
    Type: String
    Default: ''
    AllowedPattern: (^$|^[A-Za-z0-9]{32}$)
    ConstraintDescription: must be a string of 32 alphanumeric characters, if specified.
Conditions:
  ConfigureCheckTXTRecordSet: !Not [ !Equals [ !Ref CheckTXTValue, '' ]]
Resources:
  PublicCheckTXTRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue
        Fn::Sub: ${PublicHostedZoneStackName}-PublicHostedZone
      Name: !Sub
        - check.${PublicDomain}.
        - PublicDomain: !ImportValue
            Fn::Sub: ${PublicHostedZoneStackName}-PublicDomain
      Type: TXT
      TTL: 1800
      ResourceRecords:
        - !Sub '"${CheckTXTValue}"'
    Condition: ConfigureCheckTXTRecordSet
