AWSTemplateFormatVersion: 2010-09-09
Description: Example-KeyPairCustomResource Template.
  This demonstrates how to import an existing SSH Key as a KeyPair, using the existing Key's Public Key.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BaselineStackName
      - Label:
          default: KeyPair Configuration
        Parameters:
          - TUserPublicKey
    ParameterLabels:
      BaselineStackName:
        default: Baseline Stack Name
      TUserPublicKey:
        default: TUser PublicKey
Parameters:
  BaselineStackName:
    Description: Name of the CloudFormation Stack containing the Baseline Resources
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Baseline
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TUserPublicKey:
    Description: Optional public key for the tuser KeyPair
    Type: String
    NoEcho: true
    Default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk/aZb7vePtFIX0IQiWv0bKr3prPnIwiDS7aCxxiK6C6Sa7ws2M8/sbJwjRNAE8xRC\
      YOob2wC5tPHhRvKOCvABx0CAci/i7yjy72Pqiyu2fkaB2jIYkJQJn0aP6H+bbcur/leLnLTnnvBx1Bc0gSFVS4ekgzxAAMgC+aHXTJqKSRqG9SMs\
      r0FWdFs3lNd9yNgYtC+AdWr3KVfKIhACFpt1oRH+4tgu3n/uEIdv7/qLtlmIXv7rJfDXWtiEKWMrwaIVxayklw/ejejuixpRBpBgTPYbsSmBsaYc\
      6Wtrxl33Kza0cft/6PA0ldzT13DEaqghuNtAWs8Khp0gBQv4aY6ttC6yNYvF/dS6YWLrHABwgQEUIClXAL7NyDVcjVi7IIK+xFVZVwzvrtDGlW9H\
      rqGhFSVlkwImaobKIFGGym2YOgwBBv7EbStlbSXeYXldtG/2MHV4YhzPWO3yVMBjpKHo5XB434nGfXEVk1aL+aRECWp9GIcBIzdiw/JTANrNA5gN\
      2jyJTc0Tya8aUFztLezlGxBLkfxSt5XVFmZaT5oV+ugjRIjPaAL9ec/H8wUig8qhRTBz2hBcpgyIadYPpMQ9WcbvoI0K39aSZcnO2ZLJiGwoS4Ld\
      Hnx3hRV0J+TCIsGIjTwdcRLVmVPGtZpmVBcwYG0+OUAr13yBO+Ecyguhmw== tuser@dxcanalyticsplatform.com"
    AllowedPattern: (^$|^ssh-rsa AAAAB3NzaC1yc2E[=/+A-Za-z0-9]{701}( .*)?$)
    ConstraintDescription: must be a valid Public Key in OpenSSH format, if specified.
Conditions:
  ConfigureTUserKeyPair: !Not [ !Equals [ !Ref TUserPublicKey, '' ]]
Resources:
  TUserKeyPair:
    Type: Custom::KeyPair
    Properties:
      ServiceToken: !ImportValue
        Fn::Sub: ${BaselineStackName}-KeyPairFunctionArn
      KeyName: tuser
      PublicKey: !Ref TUserPublicKey
    Condition: ConfigureTUserKeyPair
Outputs:
  TUserKeyPair:
    Description: The TUser KeyPair
    Value: !Ref TUserKeyPair
    Export:
      Name: !Sub ${AWS::StackName}-TUserKeyPair
    Condition: ConfigureTUserKeyPair
  TUserKeyPairFingerprint:
    Description: The TUser KeyPair Fingerprint
    Value: !GetAtt TUserKeyPair.Fingerprint
    Condition: ConfigureTUserKeyPair
