AWSTemplateFormatVersion: 2010-09-09
Description: Example-WindowsImageCustomResource Template.
  This demonstrates how to dynamically get the most recent Windows Image.
Parameters:
  Region:
    Description: Optional Region, specify to select a region other than the current region
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank.
  Version:
    Description: Windows Version
    Type: String
    Default: Windows Server 2012 R2
    AllowedValues:
      - ''
      - Windows Server 2016
      - Windows Server 2016 with Containers
      - Windows Server 2016 Nano
      - Windows Server 2016 with SQL Server 2016 Express
      - Windows Server 2016 with SQL Server 2016 Web
      - Windows Server 2016 with SQL Server Standard
      - Windows Server 2012 R2
      - Windows Server 2012 R2 with SQL Server 2016 Express
      - Windows Server 2012 R2 with SQL Server 2016 Web
      - Windows Server 2012 R2 with SQL Server 2016 Standard
    ConstraintDescription: Must be a valid Windows version or blank.
  Date:
    Description: Optional Windows Date, specify to select a specific publication date for the Image
    Type: String
    Default: 20190712
    AllowedPattern: (^$|^20(1[6-9]|[2-9][0-9])(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$)
    ConstraintDescription: Must be a valid date or blank.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureVersion: !Not [ !Equals [ !Ref Version, '' ]]
  ConfigureDate: !Not [ !Equals [ !Ref Date, '' ]]
Resources:
  LatestWindowsImage:
    Type: Custom::WindowsImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:WindowsImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
  LatestVersionedWindowsImage:
    Type: Custom::WindowsImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:WindowsImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
  SpecificVersionedWindowsImage:
    Type: Custom::WindowsImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:WindowsImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
      OSDate: !If
        - ConfigureDate
        - !Ref Date
        - !Ref AWS::NoValue
Outputs:
  LatestImageId:
    Description: The Latest ImageId
    Value: !Ref LatestWindowsImage
  LatestName:
    Description: The Latest Image Name
    Value: !GetAtt LatestWindowsImage.Name
  LatestVersionedImageId:
    Description: The Latest Versioned ImageId
    Value: !Ref LatestVersionedWindowsImage
  LatestVersionedName:
    Description: The Latest Versioned Image Name
    Value: !GetAtt LatestVersionedWindowsImage.Name
  SpecificVersionedImageId:
    Description: The Specific Versioned ImageId
    Value: !Ref SpecificVersionedWindowsImage
  SpecificVersionedName:
    Description: The Specific Versioned Image Name
    Value: !GetAtt SpecificVersionedWindowsImage.Name
