AWSTemplateFormatVersion: 2010-09-09
Description: Example-CISCentosImageCustomResource Template.
  This demonstrates how to dynamically get the most recent Center for Internet Security Centos Image.
Parameters:
  Region:
    Description: Optional Region, specify to select a region other than the current region
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank.
  Version:
    Description: Centos Version
    Type: String
    Default: Centos 6
    AllowedValues:
      - ''
      - Centos 7
      - Centos 6
    ConstraintDescription: Must be a valid Centos version or blank.
  CISBenchmark:
    Description: Optional CIS Benchmark, specify to select a specific benchmark for the Image
    Type: String
    Default: 2.0.2.10
    AllowedPattern: (^$|^[0-9]\.[0-9]\.([0-9]|[1-9][0-9])\.([0-9]|[1-9][0-9])$)
    ConstraintDescription: Must be a valid benchmark of the form x.x.x.x or blank.
  CISLevel:
    Description: Optional CIS Level, specify to select a specific level for the Image
    Type: String
    Default: 1
    AllowedValues:
      - ''
      - 1
      - 2
    ConstraintDescription: Must be 1, 2 or blank.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureVersion: !Not [ !Equals [ !Ref Version, '' ]]
  ConfigureCISBenchmark: !Not [ !Equals [ !Ref CISBenchmark, '' ]]
  ConfigureCISLevel: !Not [ !Equals [ !Ref CISLevel, '' ]]
Resources:
  LatestCISCentosImage:
    Type: Custom::CISCentosImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CISCentosImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      CISLevel: !If
        - ConfigureCISLevel
        - !Ref CISLevel
        - !Ref AWS::NoValue
  LatestVersionedCISCentosImage:
    Type: Custom::CISCentosImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CISCentosImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
      CISLevel: !If
        - ConfigureCISLevel
        - !Ref CISLevel
        - !Ref AWS::NoValue
  SpecificVersionedCISCentosImage:
    Type: Custom::CISCentosImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CISCentosImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
      CISBenchmark: !If
        - ConfigureCISBenchmark
        - !Ref CISBenchmark
        - !Ref AWS::NoValue
      CISLevel: !If
        - ConfigureCISLevel
        - !Ref CISLevel
        - !Ref AWS::NoValue
Outputs:
  LatestImageId:
    Description: The Latest ImageId
    Value: !Ref LatestCISCentosImage
  LatestName:
    Description: The Latest Image Name
    Value: !GetAtt LatestCISCentosImage.Name
  LatestVersionedImageId:
    Description: The Latest Versioned ImageId
    Value: !Ref LatestVersionedCISCentosImage
  LatestVersionedName:
    Description: The Latest Versioned Image Name
    Value: !GetAtt LatestVersionedCISCentosImage.Name
  SpecificVersionedImageId:
    Description: The Specific Versioned ImageId
    Value: !Ref SpecificVersionedCISCentosImage
  SpecificVersionedName:
    Description: The Specific Versioned Image Name
    Value: !GetAtt SpecificVersionedCISCentosImage.Name
