AWSTemplateFormatVersion: 2010-09-09
Description: Example-SamlIdentityProviderCustomResource Template.
  This demonstrates how to create a SAML Identity Provider via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - SamlProviderName
          - SamlProviderMetadata
          - SamlProviderMetadataUrl
    ParameterLabels:
      SamlProviderName:
        default: SAML Provider Name
      SamlProviderMetadata:
        default: SAML Provider Metadata
      SamlProviderMetadataUrl:
        default: SAML Provider Metadata URL
Parameters:
  SamlProviderName:
    Description: Name of the SAML Provider associated with the Stack
    Type: String
  ProviderMetadata:
    Description: XML Metadata of the SAML Provider associated with the Stack
    Type: String
Conditions:
  ConfigureMetadata: !Not [ !Equals [ !Ref SamlProviderMetadata, '' ]]
  ConfigureMetadataUrl: !Not [ !Condition ConfigureMetadata ]
Resources:
  MetadataDownloader:
    Type: Custom::MetadataDownloader
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:MetadataDownloader
      MetadataUrl: !Ref SamlProviderMetadataUrl
    Condition: ConfigureMetadataUrl
  SamlProvider:
    Type: Custom::SamlProvider
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SamlProvider
      ProviderName: !Ref SamlProviderName
      ProviderMetadata: !If
        - ConfigureMetadata
        - !Ref SamlProviderMetadata
        - !If
            - ConfigureMetadataUrl
            - !GetAtt MetadataDownloader.Metadata
            - !Ref AWS::NoValue
Outputs:
  SamlProviderArn:
    Description: The SAML Provider ARN
    Value: !GetAtt SamlProvider.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SamlProviderArn
