AWSTemplateFormatVersion: 2010-09-09
Description: Example-VpcDefaultResourceTaggerCustomResource Template.
  This demonstrates how to tag resources created when a VPC is created, but which are by default untagged.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Configuration
        Parameters:
          - EnvironmentName
          - Network
      - Label:
          default: Name Tag Replacement Text
        Parameters:
          - VpcNameTagReplaceText
          - RouteTableNameTagReplaceText
          - NetworkAclNameTagReplaceText
          - SecurityGroupNameTagReplaceText
    ParameterLabels:
      EnvironmentName:
        default: Environment Name
      Network:
        default: Network
      VpcNameTagReplaceText:
        default: VPC
      RouteTableNameTagReplaceText:
        default: RouteTable
      NetworkAclNameTagReplaceText:
        default: NetworkAcl
      SecurityGroupNameTagReplaceText:
        default: SecurityGroup
Parameters:
  EnvironmentName:
    Description: Name of the Environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
      - Management
      - Organization
    ConstraintDescription: must be Production, Staging, UAT, Testing, Development, Build, Core, Recovery, Log, Identity, Management or Organization.
  Network:
    Description: VPC Network
    Type: String
    Default: 172.21.0.0/21
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-7]))$
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/16-27.
  VpcNameTagReplaceText:
    Description: Optional Text to replace in the VPC Name Tag (defaults to VPC)
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[a-zA-Z0-9][-a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an alphanumeric character and contain alphanumeric characters and dashes, if specified.
  RouteTableNameTagReplaceText:
    Description: Optional Text to use in the RouteTable Name Tag (defaults to MainRouteTable)
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[a-zA-Z0-9][-a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an alphanumeric character and contain alphanumeric characters and dashes, if specified.
  NetworkAclNameTagReplaceText:
    Description: Optional Text to use in the NetworkAcl Name Tag (defaults to DefaultNetworkAcl)
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[a-zA-Z0-9][-a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an alphanumeric character and contain alphanumeric characters and dashes, if specified.
  SecurityGroupNameTagReplaceText:
    Description: Optional Text to use in the SecurityGroup Name Tag (defaults to DefaultSecurityGroup)
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[a-zA-Z0-9][-a-zA-Z0-9]*$)
    ConstraintDescription: must begin with an alphanumeric character and contain alphanumeric characters and dashes, if specified.
Conditions:
  ConfigureVpcNameTagReplaceText: !Not [ !Equals [ !Ref VpcNameTagReplaceText, '' ]]
  ConfigureRouteTableNameTagReplaceText: !Not [ !Equals [ !Ref RouteTableNameTagReplaceText, '' ]]
  ConfigureNetworkAclNameTagReplaceText: !Not [ !Equals [ !Ref NetworkAclNameTagReplaceText, '' ]]
  ConfigureSecurityGroupNameTagReplaceText: !Not [ !Equals [ !Ref SecurityGroupNameTagReplaceText, '' ]]
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref Network
      Tags:
        - Key: Name
          Value: !If
            - ConfigureVpcNameTagReplaceText
            - !Sub ${EnvironmentName}-${VpcNameTagReplaceText}
            - !Sub ${EnvironmentName}-VPC
        - Key: Environment
          Value: !Ref EnvironmentName
  VpcDefaultResourceTagger:
    Type: Custom::VpcDefaultResourceTagger
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:VpcDefaultResourceTagger
      VpcId: !Ref VPC
      VpcNameTagReplaceText: !If [ ConfigureVpcNameTagReplaceText, !Ref VpcNameTagReplaceText, !Ref 'AWS::NoValue' ]
      RouteTableNameTagReplaceText: !If [ ConfigureRouteTableNameTagReplaceText, !Ref RouteTableNameTagReplaceText, !Ref 'AWS::NoValue' ]
      NetworkAclNameTagReplaceText: !If [ ConfigureNetworkAclNameTagReplaceText, !Ref NetworkAclNameTagReplaceText, !Ref 'AWS::NoValue' ]
      SecurityGroupNameTagReplaceText: !If [ ConfigureSecurityGroupNameTagReplaceText, !Ref SecurityGroupNameTagReplaceText, !Ref 'AWS::NoValue' ]
