AWSTemplateFormatVersion: 2010-09-09
Description: Example-DeepSecurityImageCustomResource Template.
  This demonstrates how to dynamically get the most recent Trend Micro Deep Security Image.
Parameters:
  Region:
    Description: Optional Region, specify to select a region other than the current region
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank.
  License:
    Description: Deep Security License. Used to select the Deep Security AMI, which can be PerHost or BYOL
    Type: String
    Default: PerHost
    AllowedValues:
      - ''
      - PerHost
      - BYOL
    ConstraintDescription: must be PerHost, BYOL or blank.
  Version:
    Description: Deep Security Version. Used to select a prior Deep Security version if non-blank
    Type: String
    Default: 11.3.184
    AllowedPattern: (^$|^[0-9]*\.[0-9]*\.[0-9]*$)
    ConstraintDescription: must be a version of the form x.y.z or blank.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureLicense: !Not [ !Equals [ !Ref License, '' ]]
  ConfigureVersion: !Not [ !Equals [ !Ref Version, '' ]]
Resources:
  LatestDeepSecurityImage:
    Type: Custom::DeepSecurityImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DeepSecurityImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
  LatestLicensedDeepSecurityImage:
    Type: Custom::DeepSecurityImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DeepSecurityImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      License: !If
        - ConfigureLicense
        - !Ref License
        - !Ref AWS::NoValue
  SpecificLicensedDeepSecurityImage:
    Type: Custom::DeepSecurityImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DeepSecurityImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      License: !If
        - ConfigureLicense
        - !Ref License
        - !Ref AWS::NoValue
      Version: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
Outputs:
  LatestImageId:
    Description: The Latest ImageId
    Value: !Ref LatestDeepSecurityImage
  LatestName:
    Description: The Latest Image Name
    Value: !GetAtt LatestDeepSecurityImage.Name
  LatestLicensedImageId:
    Description: The Latest Licensed ImageId
    Value: !Ref LatestLicensedDeepSecurityImage
  LatestLicensedName:
    Description: The Latest Licensed Image Name
    Value: !GetAtt LatestLicensedDeepSecurityImage.Name
  SpecificLicensedImageId:
    Description: The Specific Licensed ImageId
    Value: !Ref SpecificLicensedDeepSecurityImage
  SpecificLicensedName:
    Description: The Specific Licensed Image Name
    Value: !GetAtt SpecificLicensedDeepSecurityImage.Name
