AWSTemplateFormatVersion: 2010-09-09
Description: Example-RHELImageCustomResource Template.
  This demonstrates how to dynamically get the most recent RHEL Image.
Parameters:
  Region:
    Description: Optional Region, specify to select a region other than the current region
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank.
  Version:
    Description: RHEL Version
    Type: String
    Default: RHEL 7.6
    AllowedValues:
      - ''
      - RHEL 7
      - RHEL 7.7
      - RHEL 7.6
      - RHEL 7.5
      - RHEL 7.4
      - RHEL 7.3
      - RHEL 7.2
      - RHEL 7.1
      - RHEL 6
      - RHEL 6.10
      - RHEL 6.9
      - RHEL 6.8
      - RHEL 6.7
    ConstraintDescription: Must be a valid RHEL version or blank.
  Date:
    Description: Optional RHEL Date, specify to select a specific publication date for the Image
    Type: String
    Default: 20181017
    AllowedPattern: (^$|^20(1[6-9]|[2-9][0-9])(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$)
    ConstraintDescription: Must be a valid date or blank.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureVersion: !Not [ !Equals [ !Ref Version, '' ]]
  ConfigureDate: !Not [ !Equals [ !Ref Date, '' ]]
Resources:
  LatestRHELImage:
    Type: Custom::RHELImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RHELImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
  LatestVersionedRHELImage:
    Type: Custom::RHELImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RHELImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
  SpecificVersionedRHELImage:
    Type: Custom::RHELImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RHELImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      OSName: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
      OSDate: !If
        - ConfigureDate
        - !Ref Date
        - !Ref AWS::NoValue
Outputs:
  LatestImageId:
    Description: The Latest ImageId
    Value: !Ref LatestRHELImage
  LatestName:
    Description: The Latest Image Name
    Value: !GetAtt LatestRHELImage.Name
  LatestVersionedImageId:
    Description: The Latest Versioned ImageId
    Value: !Ref LatestVersionedRHELImage
  LatestVersionedName:
    Description: The Latest Versioned Image Name
    Value: !GetAtt LatestVersionedRHELImage.Name
  SpecificVersionedImageId:
    Description: The Specific Versioned ImageId
    Value: !Ref SpecificVersionedRHELImage
  SpecificVersionedName:
    Description: The Specific Versioned Image Name
    Value: !GetAtt SpecificVersionedRHELImage.Name
