AWSTemplateFormatVersion: 2010-09-09
Description: Example-RoleReferenceCustomResource Template.
  This demonstrates how to create a Reference to a Role which may exist in another Region and/or Account via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - AccountId
          - RoleName
    ParameterLabels:
      AccountId:
        default: Account Id
      RoleName:
        default: Role Name
Parameters:
  AccountId:
    Description: Optional Account which contains the Role
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid 12-digit AWS Account Id, if specified.
  RoleName:
    Description: Name of the Role
    Type: String
    Default: Administrators
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
Conditions:
  ConfigureAccountId: !Not [ !Equals [ !Ref AccountId, '' ]]
Resources:
  RoleReference:
    Type: Custom::RoleReference
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RoleReference
      AccountId: !If
        - ConfigureAccountId
        - !Ref AccountId
        - !Ref AWS::NoValue
      RoleName: !Ref RoleName
Outputs:
  RoleName:
    Description: The Role Name
    Value: !Ref RoleReference
  RoleArn:
    Description: The Role Arn
    Value: !GetAtt RoleReference.Arn
  RoleId:
    Description: The Role Id
    Value: !GetAtt RoleReference.RoleId
