AWSTemplateFormatVersion: 2010-09-09
Description: Example-RandomPasswordCustomResource Template.
  This demonstrates how to use the RandomPassword Lambda Function to create a Random Password.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BaselineStackName
      - Label:
          default: Random Password Configuration
        Parameters:
          - PasswordLength
          - ExcludeUppercase
          - ExcludeLowercase
          - ExcludeNumbers
          - ExcludePunctuation
          - IncludeSpace
          - RequireEachIncludedType
          - ExcludeCharacters
    ParameterLabels:
      BaselineStackName:
        default: Baseline Stack Name
      PasswordLength:
        default: Password Length
      ExcludeUppercase:
        default: Exclude Uppercase
      ExcludeLowercase:
        default: Exclude Lowercase
      ExcludeNumbers:
        default: Exclude Numbers
      ExcludePunctuation:
        default: Exclude Punctuation
      IncludeSpace:
        default: Include Space
      RequireEachIncludedType:
        default: Require Each Included Type
      ExcludeCharacters:
        default: Exclude Characters
Parameters:
  BaselineStackName:
    Description: Name of the CloudFormation Stack containing the Baseline Resources
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Baseline
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  PasswordLength:
    Description: Length of Random Password to generate
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - 4
      - 8
      - 12
      - 16
      - 20
      - 24
      - 32
      - 64
    ConstraintDescription: must be (blank) 4, 8, 12, 16, 20, 24, 32 or 64.
  ExcludeUppercase:
    Description: Exclude uppercase
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  ExcludeLowercase:
    Description: Exclude lowercase
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  ExcludeNumbers:
    Description: Exclude numbers
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  ExcludePunctuation:
    Description: Exclude punctuation
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  IncludeSpace:
    Description: Include space
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  RequireEachIncludedType:
    Description: Require each included type
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  ExcludeCharacters:
    Description: Characters which should not appear in the result
    Type: String
    Default: ''
Conditions:
  ConfigurePasswordLength: !Not [ !Equals [ !Ref PasswordLength, '' ]]
  ConfigureExcludeUppercase: !Equals [ !Ref ExcludeUppercase, true ]
  ConfigureExcludeLowercase: !Equals [ !Ref ExcludeLowercase, true ]
  ConfigureExcludeNumbers: !Equals [ !Ref ExcludeNumbers, true ]
  ConfigureExcludePunctuation: !Equals [ !Ref ExcludePunctuation, true ]
  ConfigureIncludeSpace: !Equals [ !Ref IncludeSpace, true ]
  ConfigureRequireEachIncludedType: !Equals [ !Ref RequireEachIncludedType, false ]
  ConfigureExcludeCharacters: !Not [ !Equals [ !Ref ExcludeCharacters, '' ]]
Resources:
  RandomPassword:
    Type: Custom::RandomPassword
    Properties:
      ServiceToken: !ImportValue
        Fn::Sub: ${BaselineStackName}-RandomPasswordFunctionArn
      PasswordLength: !If [ ConfigurePasswordLength, !Ref PasswordLength, !Ref 'AWS::NoValue' ]
      ExcludeUppercase: !If [ ConfigureExcludeUppercase, !Ref ExcludeUppercase, !Ref 'AWS::NoValue' ]
      ExcludeLowercase: !If [ ConfigureExcludeLowercase, !Ref ExcludeLowercase, !Ref 'AWS::NoValue' ]
      ExcludeNumbers: !If [ ConfigureExcludeNumbers, !Ref ExcludeNumbers, !Ref 'AWS::NoValue' ]
      ExcludePunctuation: !If [ ConfigureExcludePunctuation, !Ref ExcludePunctuation, !Ref 'AWS::NoValue' ]
      IncludeSpace: !If [ ConfigureIncludeSpace, !Ref IncludeSpace, !Ref 'AWS::NoValue' ]
      RequireEachIncludedType: !If [ ConfigureRequireEachIncludedType, !Ref RequireEachIncludedType, !Ref 'AWS::NoValue' ]
      ExcludeCharacters: !If [ ConfigureExcludeCharacters, !Ref ExcludeCharacters, !Ref 'AWS::NoValue' ]
Outputs:
  RandomPassword:
    Description: The RandomPassword
    Value: !GetAtt RandomPassword.Password
