AWSTemplateFormatVersion: 2010-09-09
Description: Example-CrossAccountStackExportCustomResource Template.
  This demonstrates how to create a Cross-Account Stack Export Lookup Capability via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - Region
          - AccountId
          - StackName
          - ExportName
    ParameterLabels:
      Region:
        default: Region
      AccountId:
        default: Account Id
      StackName:
        default: Stack Name
      ExportName:
        default: Export Name
Parameters:
  Region:
    Description: Region which contains the Export
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank (to use current Region).
  AccountId:
    Description: Account which contains the Export
    Type: String
    Default: 799051511999
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid 12-digit AWS Account Id or blank (to use current Account Id).
  StackName:
    Description: Name of the CloudFormation Stack containing the Export (Used as prefix for Export Name)
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Topics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  ExportName:
    Description: Name of the Export (Will be appended to StackName with a dash to construct full Export Name)
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: EventsTopic
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureAccountId: !Not [ !Equals [ !Ref AccountId, '' ]]
Resources:
  StackExportReference:
    Type: Custom::CrossAccountStackExport
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CrossAccountStackExport
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      AccountId: !If
        - ConfigureAccountId
        - !Ref AccountId
        - !Ref AWS::NoValue
      ExportName: !Sub ${StackName}-${ExportName}
Outputs:
  StackExportValue:
    Description: The Stack Export Value
    Value: !Ref StackExportReference
