AWSTemplateFormatVersion: 2010-09-09
Description: Example-CrossAccountVpcCustomResource Template.
  This demonstrates how to create a Cross-Account VPC Lookup Capability via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - Region
          - AccountId
          - VpcName
    ParameterLabels:
      Region:
        default: Region
      AccountId:
        default: Account Id
      VpcName:
        default: VPC Name
Parameters:
  Region:
    Description: Region which contains the VPC
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank (to use current Region).
  AccountId:
    Description: Account which contains the VPC
    Type: String
    Default: 799051511999
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid 12-digit AWS Account Id or blank (to use current Account Id).
  VpcName:
    Description: Name of the VPC (Value used for Name Tag)
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Default-VPC
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureAccountId: !Not [ !Equals [ !Ref AccountId, '' ]]
Resources:
  VpcReference:
    Type: Custom::CrossAccountVpc
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CrossAccountVpc
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      AccountId: !If
        - ConfigureAccountId
        - !Ref AccountId
        - !Ref AWS::NoValue
      VpcName: !Ref VpcName
Outputs:
  VpcId:
    Description: The VPC Id
    Value: !Ref VpcReference
  VpcNetwork:
    Description: The VPC Network
    Value: !GetAtt VpcReference.CidrBlock
