AWSTemplateFormatVersion: 2010-09-09
Description: Example-DomainNameServersCustomResource Template.
  This demonstrates how to update a Route53 Domain's Name Servers via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
      - Label:
          default: Function Configuration
        Parameters:
          - EnvironmentName
          - PublicDomain
    ParameterLabels:
      EnvironmentName:
        default: Environment Name
      PublicDomain:
        default: Public Domain Name
Parameters:
  EnvironmentName:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
      - Management
      - Organization
    ConstraintDescription: must be Production, Staging, UAT, Testing, Development, Build, Core, Recovery, Log, Identity, Management or Organization.
  PublicDomain:
    Description: Name of the Public Domain
    Type: String
    Default: us-west-2.hlsb.dxcanalytics.com
Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub Public Zone for ${PublicDomain}
      Name: !Sub ${PublicDomain}.
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicHostedZone
  DomainNameServers:
    Type: Custom::DomainNameServers
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DomainNameServers
      DomainName: !Ref PublicDomain
      NameServers: !GetAtt PublicHostedZone.NameServers
Outputs:
  PublicDomain:
    Description: The PublicDomain
    Value: !Ref PublicDomain
    Export:
      Name: !Sub ${AWS::StackName}-PublicDomain
  PublicHostedZone:
    Description: The PublicHostedZone
    Value: !Ref PublicHostedZone
    Export:
      Name: !Sub ${AWS::StackName}-PublicHostedZone
