AWSTemplateFormatVersion: 2010-09-09
Description: Identity-SamlIdentityProvider Template.
  This creates an IAM SAML Identity Provider.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BaselineStackName
      - Label:
          default: Identity Provider Configuration
        Parameters:
          - SamlProviderName
          - SamlProviderType
          - SamlProviderMetadata
          - SamlProviderMetadataUrl
          - SamlProviderAccessMethod
          - SamlProviderMasterAccount
    ParameterLabels:
      BaselineStackName:
        default: Baseline Stack Name
      SamlProviderName:
        default: SAML Provider Name
      SamlProviderType:
        default: SAML Provider Type
      SamlProviderMetadata:
        default: SAML Provider Metadata
      SamlProviderMetadataUrl:
        default: SAML Provider Metadata URL
      SamlProviderAccessMethod:
        default: SAML Provider Access Method
      SamlProviderMasterAccount:
        default: SAML Provider Master Account
Parameters:
  BaselineStackName:
    Description: Name of the CloudFormation Stack containing Baseline Resources
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Baseline
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  SamlProviderName:
    Description: Name of the SAML Provider associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: dxcap.okta.com
    AllowedPattern: ^[-.a-zA-Z0-9]*$
    ConstraintDescription: must contain alphanumeric characters, dashes and periods.
  SamlProviderType:
    Description: Type of SAML Provider associated with the Stack
    Type: String
    Default: okta
    AllowedValues:
      - duo
      - okta
    ConstraintDescription: must be duo or okta.
  SamlProviderMetadata:
    Description: XML Metadata of the SAML Provider associated with the Stack
    Type: String
    Default: ''
  SamlProviderMetadataUrl:
    Description: URL to download XML Metadata of the SAML Provider associated with the Stack
    Type: String
    Default: ''
  SamlProviderAccessMethod:
    Description: Method by which the SAML Provider will integrate with this Account
    Type: String
    Default: single
    AllowedValues:
      - single
      - master
      - child
    ConstraintDescription: must be single, master or child.
  SamlProviderMasterAccount:
    Description: AWS Account ID of the SAML Provider Master Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID. Required when SamlProviderAccessMethod is child.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
  ValidateSamlProviderMetadata:
    RuleCondition: !Equals [ !Ref SamlProviderMetadataUrl, '' ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref SamlProviderMetadata, '' ]]
        AssertDescription: SamlProviderMetadata required when SamlProviderMetadataUrl is blank
  ValidateSamlProviderMetadataUrl:
    RuleCondition: !Equals [ !Ref SamlProviderMetadata, '' ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref SamlProviderMetadataUrl, '' ]]
        AssertDescription: SamlProviderMetadataUrl required when SamlProviderMetadata is blank
  ValidateSamlProviderMasterAccount:
    RuleCondition: !Equals [ !Ref SamlProviderAccessMethod, child ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref SamlProviderMasterAccount, '' ]]
        AssertDescription: SamlProviderMasterAccount required when SamlProviderAccessMethod is child
Conditions:
  ConfigureOkta: !Equals [ !Ref SamlProviderType, okta ]
  ConfigureDuo: !Equals [ !Ref SamlProviderType, duo ]
  ConfigureOktaSingleAccount: !And [ !Condition ConfigureOkta, !Equals [ !Ref SamlProviderAccessMethod, single ]]
  ConfigureOktaMultipleAccountMaster: !And [ !Condition ConfigureOkta, !Equals [ !Ref SamlProviderAccessMethod, master ]]
  ConfigureOktaMultipleAccountChild: !And [ !Condition ConfigureOkta, !Equals [ !Ref SamlProviderAccessMethod, child ]]
  ConfigureMetadata: !Not [ !Equals [ !Ref SamlProviderMetadata, '' ]]
  ConfigureMetadataUrl: !Not [ !Condition ConfigureMetadata ]
Resources:
  OktaSingleAccountUser:
    Type: AWS::IAM::User
    Properties:
      UserName: okta
      Path: /
      Policies:
        - PolicyName: OktaSingleAccountPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:ListAccountAliases
                Resource: '*'
    Condition: ConfigureOktaSingleAccount
  OktaMultipleAccountMasterUser:
    Type: AWS::IAM::User
    Properties:
      UserName: okta
      Path: /
      Policies:
        - PolicyName: OktaMultipleAccountMasterPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:ListAccountAliases
                  - iam:GetAccountSummary
                  - iam:GetUser
                  - sts:AssumeRole
                Resource: '*'
    Condition: ConfigureOktaMultipleAccountMaster
  OktaMultipleAccountChildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Okta-Idp-cross-account-role # This exact name is required - do not change
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${SamlProviderMasterAccount}:root
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: OktaMultipleAccountChildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:ListAccountAliases
                Resource: '*'
    Condition: ConfigureOktaMultipleAccountChild
  MetadataDownloader:
    Type: Custom::MetadataDownloader
    Properties:
      ServiceToken: !ImportValue
        Fn::Sub: ${BaselineStackName}-MetadataDownloaderFunctionArn
      MetadataUrl: !Ref SamlProviderMetadataUrl
    Condition: ConfigureMetadataUrl
  SamlProvider:
    Type: Custom::SamlProvider
    Properties:
      ServiceToken: !ImportValue
        Fn::Sub: ${BaselineStackName}-SamlProviderFunctionArn
      ProviderName: !Ref SamlProviderName
      ProviderMetadata: !If
        - ConfigureMetadata
        - !Ref SamlProviderMetadata
        - !If
            - ConfigureMetadataUrl
            - !GetAtt MetadataDownloader.Metadata
            - !Ref AWS::NoValue
Outputs:
  SamlProviderArn:
    Description: The SAML Provider ARN
    Value: !GetAtt SamlProvider.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SamlProviderArn
