AWSTemplateFormatVersion: 2010-09-09
Description: Identity-MultiAccountManagedPolicies Template.
  This creates Multi-Account IAM ManagedPolicies, meant to be assumed by CustomResources running in another Account.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Resources:
  ReferenceAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ReferenceAccess
      Description: Provides read-only access to a limited set of AWS services and resources.
        Used in Multi-Account configurations for References to Resources in another Account.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowGetRole
            Effect: Allow
            Action:
              - iam:ListRoles
              - iam:GetRole
            Resource: '*'
          - Sid: AllowDescribeVpcs
            Effect: Allow
            Action:
              - ec2:DescribeVpcs
            Resource: '*'
          - Sid: AllowDescribeSubnets
            Effect: Allow
            Action:
              - ec2:DescribeSubnets
            Resource: '*'
          - Sid: AllowDescribeSecurityGroups
            Effect: Allow
            Action:
              - ec2:DescribeSecurityGroups
            Resource: '*'
          - Sid: AllowListExports
            Effect: Allow
            Action:
              - cloudformation:ListExports
            Resource: '*'
          - Sid: AllowDescribeStacks
            Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource: '*'
          - Sid: AllowListBuckets
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: '*'
  VPCPeeringConnectionAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: VPCPeeringConnectionAccess
      Description: Provides an ability to setup VPC Peering Connections with a VPC in another Account.
        Used in Multi-Account configurations for VPC Peering Connections between Accounts.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAcceptVpcPeeringConnection
            Effect: Allow
            Action:
              - ec2:AcceptVpcPeeringConnection
            Resource: '*'
  HostedZoneDelegationProxyAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: HostedZoneDelegationProxyAccess
      Description: Provides an ability to call a proxy Lambda Function which can manage Sub-Domain delegations in a HostedZone.
        Used in Multi-Account configurations for update of Parent Domain Name Server delegation records in another Account.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowInvokeLambda
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub arn:aws:lambda:*:${AWS::AccountId}:function:HostedZoneDelegation
  DomainNameServersProxyAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DomainNameServersProxyAccess
      Description: Provides an ability to call a proxy Lambda Function which can update NameServers in a Route53 Domain.
        Used in Multi-Account configurations for update of Domain Name Servers in another Account.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowInvokeLambda
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub arn:aws:lambda:*:${AWS::AccountId}:function:DomainNameServers
Outputs:
  ReferenceAccess:
    Description: The ReferenceAccess ManagedPolicy ARN
    Value: !Ref ReferenceAccess
    Export:
      Name: !Sub ${AWS::StackName}-ReferenceAccess
  VPCPeeringConnectionAccess:
    Description: The VPCPeeringConnectionAccess ManagedPolicy ARN
    Value: !Ref VPCPeeringConnectionAccess
    Export:
      Name: !Sub ${AWS::StackName}-VPCPeeringConnectionAccess
  HostedZoneDelegationProxyAccess:
    Description: The HostedZoneDelegationProxyAccess ManagedPolicy ARN
    Value: !Ref HostedZoneDelegationProxyAccess
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneDelegationProxyAccess
  DomainNameServersProxyAccess:
    Description: The DomainNameServersProxyAccess ManagedPolicy ARN
    Value: !Ref DomainNameServersProxyAccess
    Export:
      Name: !Sub ${AWS::StackName}-DomainNameServersProxyAccess
