AWSTemplateFormatVersion: 2010-09-09
Description: Identity-CustomRoles Template.
  This creates Custom IAM Roles. These are not Application specific - Roles created here are for Federated Identity and Cross-Account Access. Roles should be kept in 1:1 sync with Groups, to insure IAM Users and Federated Users have the same permissions.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - CustomManagedPoliciesStackName
          - ManagedPoliciesStackName
      - Label:
          default: Identity Provider Dependencies
        Parameters:
          - SamlProviderName
      - Label:
          default: Account Dependencies
        Parameters:
          - AdministratorAccount
    ParameterLabels:
      CustomManagedPoliciesStackName:
        default: Custom ManagedPolicies Stack Name
      ManagedPoliciesStackName:
        default: ManagedPolicies Stack Name
      SamlProviderName:
        default: SAML Provider Name
      AdministratorAccount:
        default: Administrator Account
Parameters:
  CustomManagedPoliciesStackName:
    Description: Name of the CloudFormation Stack containing Custom ManagedPolicies
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: CustomManagedPolicies
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  ManagedPoliciesStackName:
    Description: Name of the CloudFormation Stack containing ManagedPolicies
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: ManagedPolicies
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  SamlProviderName:
    Description: Name of the SAML Provider
    Type: String
    Default: ''
    AllowedPattern: (^$|^[-.a-zA-Z0-9]{2,64}$)
    ConstraintDescription: must begin with a letter and contain alphanumeric characters, dashes and periods, or blank.
  AdministratorAccount:
    Description: AWS Account ID of the Organization Administrator Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureSamlRoles: !Not [ !Equals [ !Ref SamlProviderName, '' ]]
  ConfigureCrossAccountRoles: !Not [ !Equals [ !Ref AdministratorAccount, '' ]]
Resources:
  ApplicationAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ApplicationAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - !ImportValue
          Fn::Sub: ${CustomManagedPoliciesStackName}-ApplicationAdministratorAccess
    Condition: ConfigureSamlRoles
  TableauAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TableauAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - !ImportValue
          Fn::Sub: ${CustomManagedPoliciesStackName}-TableauAdministratorAccess
    Condition: ConfigureSamlRoles
Outputs:
  ApplicationAdministratorsRole:
    Description: The ApplicationAdministratorsRole Name
    Value: !Ref ApplicationAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationAdministratorsRole
    Condition: ConfigureSamlRoles
  TableauAdministratorsRole:
    Description: The TableauAdministratorsRole Name
    Value: !Ref TableauAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-TableauAdministratorsRole
    Condition: ConfigureSamlRoles
