AWSTemplateFormatVersion: 2010-09-09
Description: Identity-CustomManagedPolicies Template.
  This creates Custom IAM ManagedPolicies.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Resources:
  ApplicationAdministratorAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ApplicationAdministratorAccess
      Description: Provides partial access to Development AWS services and resources, needed for Application Administrators.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:RebootInstances
              - ec2:TerminateInstances
            Condition:
              StringEquals:
                ec2:ResourceTag/Environment: Development
            Resource:
              - !Sub arn:aws:ec2::${AWS::AccountId}:instance/*
  TableauAdministratorAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TableauAdministratorAccess
      Description: Provides partial access to Tableau AWS services and resources, needed for Tableau Administrators.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowUserToListBucketsInTheConsole
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource:
              - arn:aws:s3:::*
          - Sid: AllowRootListingOfBucketsContainingTableauObjects
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::products-us-east-1-dxchlsb
              - arn:aws:s3:::products-us-east-2-dxchlsb
              - arn:aws:s3:::products-us-west-2-dxchlsb
              - arn:aws:s3:::configurations-us-east-1-dxchlsb
              - arn:aws:s3:::configurations-us-east-2-dxchlsb
              - arn:aws:s3:::configurations-us-west-2-dxchlsb
            Condition:
              StringEquals:
                s3:prefix:
                  - ''
                s3:delimiter:
                  - /
          - Sid: AllowListingOfTableauFolder
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::products-us-east-1-dxchlsb
              - arn:aws:s3:::products-us-east-2-dxchlsb
              - arn:aws:s3:::products-us-west-2-dxchlsb
              - arn:aws:s3:::configurations-us-east-1-dxchlsb
              - arn:aws:s3:::configurations-us-east-2-dxchlsb
              - arn:aws:s3:::configurations-us-west-2-dxchlsb
            Condition:
              StringLike:
                s3:prefix:
                  - Tableau/*
          - Sid: AllowReadWriteActionsInTableauFolder
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource:
              - arn:aws:s3:::products-us-east-1-dxchlsb/Tableau/*
              - arn:aws:s3:::products-us-east-2-dxchlsb/Tableau/*
              - arn:aws:s3:::products-us-west-2-dxchlsb/Tableau/*
              - arn:aws:s3:::configurations-us-east-1-dxchlsb/Tableau/*
              - arn:aws:s3:::configurations-us-east-2-dxchlsb/Tableau/*
              - arn:aws:s3:::configurations-us-west-2-dxchlsb/Tableau/*
          - Sid: AllowStartStopRebootOfTableauInstancesInNonProduction
            Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:RebootInstances
            Condition:
              StringEquals:
                ec2:ResourceTag/Application: Tableau
              ForAnyValue:StringEquals:
                ec2:ResourceTag/Environment:
                  - Staging
                  - Testing
                  - Development
            Resource:
              - !Sub arn:aws:ec2::${AWS::AccountId}:instance/*
Outputs:
  ApplicationAdministratorAccess:
    Description: The ApplictionAdministratorAccess ManagedPolicy ARN
    Value: !Ref ApplicationAdministratorAccess
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationAdministratorAccess
  TableauAdministratorAccess:
    Description: The TableauAdministratorAccess ManagedPolicy ARN
    Value: !Ref TableauAdministratorAccess
    Export:
      Name: !Sub ${AWS::StackName}-TableauAdministratorAccess
